### ISSUE TITLE
Code generation broken on API 17

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly-android#219]
Works on API 23
Likely related to the differing webview implementations
Codegen fails with "04-29 16:22:11.240 1736-1736/com.google.blockly.demo E/Web Console: Uncaught SyntaxError: Unexpected token ILLEGAL at null:1

**Comment by RoboErikG** [comment]
Quick followup. I spent a little time investigating and the issue is passing special characters across the boundary on older Android platforms. I was able to get it working by manually

in Java:
- Removing all \n and \r characters.
- Replacing spaces with '%20'. (encode replaces spaces with +)
- Running the rest through URLEncoder.encode()

in JS:
- Calling unescape(). (unescape doesn't handle the spaces)
- Replacing '%20' with spaces

This is pretty fragile and dependent on the platforms implementation, so as a more robust solution we should investigate other ways of encoding or passing the data across.

**Comment by AnmAtAnm** [comment]
My gut says you want to reverse those escapings so you don't get %25;20; (percent sign escaped as %25;, followed by 20; for the remainder of the escaped space).  More specifically:

in Java:
* Collapse all \n, \t and \r characters into a single space characters.  Might want to look for a .js compression library, without identifier replacement.
* Run the result through URLEncoder.encode(), which encode spaces as '+'
* Replace '+' with '%20'.

in JS:
* Call unescape(). %20 instances correctly unescape to spaces without additional replacement.

I say this without testing it (or even looking at code).

**Comment by RoboErikG** [comment]
Good catch, Andrew. That simplifies the calls a bit. Putting together a change to make this work on older versions. We should still monitor it in case there's any other issues with older versions.
