### ISSUE TITLE
Cannot pan workspace with only a single block

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly-android#264]
There appears to be overly restrictive panning constraints that limit how far the user can pan.  I'm guessing it is measured based the further block position being at least within half the screen height of the visible edge.  However, when there is only one block, this is an obnoxiously small area to pan.

The user should be able to pan the workspace to put that block anywhere.

**Comment by RoboErikG** [comment]
The calculation should be updated to extend the workspace so that if the blocks are smaller than half the viewport they can be dragged anywhere within the view and if they're bigger there will still be half a viewport on each edge of the bounding box for all the blocks.

bottom = max (workspaceBounds.bottom + .5 * viewportHeight, workspaceBounds.bottom + (viewportHeight - workspaceBounds.height)
top = min (workspaceBounds.top - .5 * viewportHeight, workspaceBounds.top - (viewportHeight - workspaceBounds.height)

right = max (workspaceBounds.right + .5 * viewportWidth, workspaceBounds.right + (viewportWidth - workspaceBounds.width)
left = min (workspaceBounds.left - .5 * viewportWidth, workspaceBounds.left - (viewportWidth - workspaceBounds.width)
