### ISSUE TITLE
Convert test assertions to use a fluent library.

### ISSUE THREAD

**Issue by ChrisA89** [google/blockly-android#466]
Could the test cases be migrated to use [AssertJ](http://joel-costigliola.github.io/assertj/index.html) instead of the default JUnit assertions.

They are much nicer to work with.

**Comment by AnmAtAnm** [comment]
Because we're Google and we need to consider integration with our internal libraries, I have to recommend [Truth](http://google.github.io/truth/) as the potential fluent test framework. I haven't personally worked with either, but I believe you'll find it very familiar to AssertJ.  If you want to put the effort into it, I'd be happy to consider a PR that ports one or new test classes to Truth, as an exploration.

**Comment by ChrisA89** [comment]
I hadn't come across Truth. I'll have a look and see what I can do.

**Comment by AnmAtAnm** [comment]
Fixed in #473.
